# The URL the site will be built for
base_url = "https://tobbylie.me"
title = "Tobby Lie"
description = "Personal blog"

# theme = "minimal-blog"

default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
render_emoji = true
external_links_target_blank = true

[markdown.highlighting]
theme = "monokai"

[extra]
role = "Staff Software Engineer"
github = "https://github.com/tobby-lie"
linkedin = "https://www.linkedin.com/in/tobby-lie/"
email = "tobbylie@gmail.com"
into = [
  "Meandering about antique malls looking at vintage stuff",
  "Aimlessly scrolling Facebook marketplace, driving to new undiscovered parts of CO for finds",
  "Amateur bird-watching with my wife",
  "Watching movies, mostly horror (the good and the bad)",
  "Reading and often not finishing books, mostly on tech",
  "Thinking about and often not starting side projects",
]
