name: Site CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
          BUILD_FLAGS: --base-url="https://tobbylie.me"
          GITHUB_TOKEN: ${{ secrets.site-cicd }}
